"""AT-SPI accessibility bus (used only in an isolated subprocess script)."""

from typing import Any

def get_desktop_count() -> int: ...
def get_desktop(index: int) -> Any: ...
def __getattr__(name: str) -> Any: ...
