from typing import Any, Callable

class Variant:
    def __init__(
        self, format_string: str = ..., value: Any = ..., *args: Any, **kwargs: Any
    ) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def unpack(self) -> Any: ...
    def get_child_value(self, index: int) -> Variant: ...
    def n_children(self) -> int: ...

class VariantType:
    def __init__(self, string: str = ..., *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class MainLoop:
    def __init__(self, context: Any = None) -> None: ...
    def run(self) -> None: ...
    def quit(self) -> None: ...
    def is_running(self) -> bool: ...
    def get_context(self) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...

def usleep(microseconds: int) -> None: ...
def quark_from_string(string: str) -> int: ...
def timeout_add_seconds(
    interval: int, function: Callable[..., Any], *args: Any, **kwargs: Any
) -> int: ...
def timeout_add(
    interval: int, function: Callable[..., Any], *args: Any, **kwargs: Any
) -> int: ...
def idle_add(function: Callable[..., Any], *args: Any, **kwargs: Any) -> int: ...
def source_remove(tag: int) -> bool: ...
def __getattr__(name: str) -> Any: ...
