"""Minimal PyGObject stubs so pyright can type-check portal/GStreamer code."""

from typing import Any

def require_version(namespace: str, version: str) -> None: ...
def get_required_version(namespace: str) -> str | None: ...
def check_version(namespace: str, version: str) -> bool: ...
def __getattr__(name: str) -> Any: ...
